Repository the-hideout/tarkov-dev, pull requests merged in 2022-06, with the labels that each got.

#62 fix css attributes to properly display monospace fonts for code blocks
  src/App.css
Labels: UI

#64 add a Discord footer to all pages
  src/components/footer/index.css
  src/components/footer/index.js
Labels: UI

#85 Seperated 'gun' types from 'wearable' types
  src/pages/loot-tiers/index.js
Labels: bug, enhancement

#87 /loot-tier page improvements
  src/components/filter/index.js
  src/pages/loot-tiers/index.js
Labels: UI

#88 Language Switcher 🌐
  src/components/footer/index.js
  src/i18n.js
  src/pages/settings/index.css
  src/pages/settings/index.js
Labels: enhancement
