Repository the-hideout/tarkov-dev, pull requests merged in 2022-08, with the labels that each got.

#186 Automate Shebuka's map thumbnails
  .gitignore
  package-lock.json
  package.json
  scripts/generate-thumbnails.js
  src/pages/maps/index.js
Labels: enhancement

#179 French Translations
  src/translations/fr/translation.json
Labels: language

#183 Add a new 2D Reserve Map
  public/maps/reserve-2d.jpg
  src/data/maps.json
Labels: enhancement

#190 Improvements general
  .github/workflows/images.yml
  package-lock.json
  package.json
  public/images/la toubib-icon.jpg
  public/images/le mécano-icon.jpg
  public/index.html
  scripts/critical.js
Labels: enhancement

#193 Calculate flea fee factoring in Intelligence Center discount
  public/images/hideout-management-icon.png
  src/components/crafts-table/index.js
  src/features/settings/settingsSlice.js
  src/modules/flea-market-fee.js
  src/pages/bitcoin-farm-calculator/data.js
  src/pages/bitcoin-farm-calculator/index.js
Labels: enhancement

#194 Added Net PPS Filter to Containers, Rigs, and BPs
  src/components/small-item-table/index.js
  src/pages/items/backpacks/index.js
  src/pages/items/containers/index.js
  src/pages/items/rigs/index.js
Labels: enhancement

#192 WIP: Added some descriptions to items pages for better SEO
  src/pages/ammo/index.js
  src/pages/barters/index.js
  src/pages/crafts/index.js
  src/pages/items/armor/index.js
  src/pages/items/backpacks/index.js
  src/pages/items/barter-items/index.js
  src/pages/items/containers/index.js
  src/pages/items/glasses/index.js
  src/pages/items/grenades/index.js
  src/pages/items/guns/index.js
  src/pages/items/headsets/index.js
  src/pages/items/helmets/index.js
  src/pages/items/keys/index.js
  src/pages/items/mods/index.js
  src/pages/items/pistol-grips/index.js
  src/pages/items/provisions/index.js
  src/pages/items/rigs/index.js
  src/pages/items/suppressors/index.js
  src/pages/maps/index.js
  src/pages/traders/index.js
  src/pages/traders/jaeger/index.js
  src/pages/traders/mechanic/index.js
  src/pages/traders/peacekeeper/index.js
  src/pages/traders/prapor/index.js
  src/pages/traders/ragman/index.js
  src/pages/traders/skier/index.js
  src/pages/traders/therapist/index.js
Labels: enhancement

#197 Package Updates
  package-lock.json
  package.json
  scripts/generate-thumbnails.js
Labels: dependencies

#199 Load More Button
  src/pages/start/index.css
  src/pages/start/index.js
Labels: enhancement, UI

#201 Open Collective Button
  README.md
  src/components/footer/index.js
  src/components/open-collective-button/index.css
  src/components/open-collective-button/index.js
  src/pages/about/index.js
Labels: UI

#204 css enhancements
  src/components/data-table/index.js
  src/components/menu/index.css
  src/components/menu/index.js
  src/pages/ammo/index.css
  src/pages/ammo/index.js
  src/pages/barters/index.css
  src/pages/barters/index.js
  src/pages/crafts/index.css
  src/pages/crafts/index.js
  src/pages/item-tracker/index.css
  src/pages/item-tracker/index.js
  src/pages/item/index.css
  src/pages/item/index.js
  src/pages/items/armor/index.js
  src/pages/items/backpacks/index.js
  src/pages/items/barter-items/index.js
  src/pages/items/containers/index.js
  src/pages/items/glasses/index.js
  src/pages/items/grenades/index.js
  src/pages/items/guns/index.js
  src/pages/items/headsets/index.js
  src/pages/items/helmets/index.js
  src/pages/items/index.css
  src/pages/items/keys/index.js
  src/pages/items/mods/index.js
  src/pages/items/pistol-grips/index.js
  src/pages/items/provisions/index.js
  src/pages/items/rigs/index.js
  src/pages/items/suppressors/index.js
  src/pages/loot-tiers/index.css
  src/pages/loot-tiers/index.js
  src/pages/maps/index.css
  src/pages/maps/index.js
  src/pages/settings/index.css
  src/pages/settings/index.js
  src/pages/start/index.css
  src/pages/start/index.js
  src/pages/stats/index.css
  src/pages/stats/index.js
  src/pages/traders/index.css
  src/pages/traders/index.js
  src/pages/traders/jaeger/index.js
  src/pages/traders/mechanic/index.js
  src/pages/traders/peacekeeper/index.js
  src/pages/traders/prapor/index.js
  src/pages/traders/ragman/index.js
  src/pages/traders/skier/index.js
  src/pages/traders/therapist/index.js
Labels: enhancement, UI

#205 Revert react fragments
  src/components/Debug.jsx
  src/components/Map.jsx
  src/components/Time.jsx
  src/components/barter-tooltip/index.js
  src/components/barters-table/index.js
  src/components/contained-items-list/index.js
  src/components/crafts-table/index.js
  src/components/item-cost/index.js
  src/components/item-grid/index.js
  src/components/item-table/index.js
  src/components/items-for-hideout/index.js
  src/components/items-summary-table/index.js
  src/components/menu/index.js
  src/components/quests-list/index.js
  src/components/reward-cell/index.js
  src/components/small-item-table/index.js
  src/components/trader-price-cell/index.js
  src/pages/ammo/index.js
  src/pages/api-docs/index.js
  src/pages/barters/index.js
  src/pages/crafts/index.js
  src/pages/hideout/index.js
  src/pages/item/index.js
  src/pages/items/backpacks/index.js
  src/pages/items/rigs/index.js
  src/pages/settings/index.js
  src/pages/traders/jaeger/index.js
  src/pages/traders/mechanic/index.js
  src/pages/traders/peacekeeper/index.js
  src/pages/traders/prapor/index.js
  src/pages/traders/ragman/index.js
  src/pages/traders/skier/index.js
  src/pages/traders/therapist/index.js
Labels: bug

#206 Bosses
  scripts/build-sitemap.js
  src/App.css
  src/App.js
  src/components/boss-list/index.css
  src/components/boss-list/index.js
  src/components/cheeki-breeki-effect/index.css
  src/components/cheeki-breeki-effect/index.js
  src/components/menu/index.js
  src/data/boss.json
  src/features/bosses/do-fetch-bosses.js
  src/modules/format-boss-data.js
  src/pages/bosses/boss/index.css
  src/pages/bosses/boss/index.js
  src/pages/bosses/index.css
  src/pages/bosses/index.js
  src/pages/items/glasses/index.js
  src/pages/settings/index.js
  src/pages/start/index.js
Labels: enhancement, UI

#211 Fix expanded rows
  src/components/data-table/index.css
  src/components/data-table/index.js
  src/pages/items/pistol-grips/index.js
Labels: enhancement, UI

#210 Maps organization and info
  scripts/build-sitemap.js
  src/components/Map.jsx
  src/components/menu/index.js
  src/data/maps.json
  src/pages/control/index.js
  src/pages/maps/index.js
  src/pages/start/index.js
Labels: UI

#220 Loot tier item real size
  src/components/item-grid/Item.jsx
  src/features/items/do-fetch-items.js
  src/pages/loot-tiers/index.js
Labels: enhancement, UI

#227 Boss item fixes
  src/data/boss.json
Labels: bug
