Repository the-hideout/tarkov-dev, pull requests merged in 2022-09, with the labels that each got.

#230 Use API item data for boss loot, add new rig layouts
  src/components/barters-table/index.js
  src/components/boss-list/index.js
  src/components/contained-items-list/index.js
  src/components/crafts-table/index.js
  src/components/reward-cell/index.js
  src/components/small-item-table/index.js
  src/components/value-cell/index.js
  src/data/boss.json
  src/data/item-grids.json
  src/features/maps/do-fetch-maps.js
  src/modules/format-boss-data.js
  src/modules/format-cost-items.js
  src/pages/bitcoin-farm-calculator/index.js
  src/pages/bosses/boss/index.js
  src/pages/item/index.js
Labels: enhancement, UI

#235 Item Page Divider
  src/App.css
  src/pages/item/index.js
Labels: UI

#236 Contributors
  package-lock.json
  package.json
  scripts/get-contributors.js
  src/components/contributors/index.js
  src/components/footer/index.js
  src/pages/about/index.js
Labels: enhancement, UI

#243 Style fixes and more
  src/App.css
  src/components/cost-items-cell/index.css
  src/components/cost-items-cell/index.js
  src/components/crafts-table/index.css
  src/components/data-table/index.css
  src/components/filter/index.css
  src/components/footer/index.css
  src/components/item-grid/index.css
  src/components/item-image/index.css
  src/components/item-image/index.js
  src/components/item-name-cell/index.js
  src/components/item-search/index.css
  src/components/item-table/index.css
  src/components/items-for-hideout/index.css
  src/components/items-for-hideout/index.js
  src/components/menu/index.css
  src/components/menu/index.js
  src/components/property-list/index.css
  src/components/quest-items-cell/index.css
  src/components/quest-items-cell/index.js
  src/components/quests-list/index.css
  src/components/remote-control-id/index.css
  src/components/reward-cell/index.css
  src/components/reward-image/index.css
  src/components/small-item-table/index.css
  src/pages/ammo/index.js
  src/pages/api-users/index.css
  src/pages/barters/index.css
  src/pages/bitcoin-farm-calculator/index.js
  src/pages/bosses/index.css
  src/pages/crafts/index.css
  src/pages/item/index.css
  src/pages/item/index.js
  src/pages/items/backpacks/index.js
  src/pages/items/helmets/index.js
  src/pages/items/rigs/index.js
  src/pages/moobot/index.css
  src/pages/nightbot/index.css
  src/pages/settings/index.css
  src/pages/start/index.css
  src/pages/stream-elements/index.css
  src/pages/traders/index.css
Labels: enhancement, UI

#244 Make item image height dynamic
  src/components/item-image/index.js
Labels: bug, UI

#247 Add cheapest price column to tables
  src/components/barter-tooltip/index.js
  src/components/small-item-table/index.js
  src/features/barters/do-fetch-barters.js
  src/features/crafts/craftsSlice.js
  src/features/items/do-fetch-items.js
  src/modules/format-cost-items.js
  src/pages/ammo/index.js
  src/pages/item/index.js
  src/pages/items/armor/index.js
  src/pages/items/backpacks/index.js
  src/pages/items/barter-items/index.js
  src/pages/items/bsg-category/index.js
  src/pages/items/containers/index.js
  src/pages/items/glasses/index.js
  src/pages/items/grenades/index.js
  src/pages/items/guns/index.js
  src/pages/items/headsets/index.js
  src/pages/items/keys/index.js
  src/pages/items/mods/index.js
  src/pages/items/provisions/index.js
  src/pages/items/rigs/index.js
  src/pages/start/index.js
  src/pages/traders/trader/index.js
Labels: enhancement, UI
