Repository the-hideout/tarkov-dev, pull requests merged in 2022-07, with the labels that each got.

#95 Set banner to success
  src/components/menu/index.js
Labels: hold

#110 More translation
  src/components/barters-table/index.js
  src/components/crafts-table/index.js
  src/components/item-grid/Item.jsx
  src/components/items-summary-table/index.js
  src/components/property-list/index.js
  src/components/small-item-table/index.js
  src/components/trader-price-cell/index.js
  src/data/category-pages.json
  src/pages/ammo/index.js
  src/pages/barters/index.js
  src/pages/control/index.js
  src/pages/crafts/index.js
  src/pages/gun-builder/index.js
  src/pages/hideout/index.js
  src/pages/item/index.js
  src/pages/items/armor/index.js
  src/pages/items/backpacks/index.js
  src/pages/items/barter-items/index.js
  src/pages/items/bsg-category/index.js
  src/pages/items/containers/index.js
  src/pages/items/glasses/index.js
  src/pages/items/grenades/index.js
  src/pages/items/guns/index.js
  src/pages/items/headsets/index.js
  src/pages/items/helmets/index.js
  src/pages/items/index.js
  src/pages/items/keys/index.js
  src/pages/items/mods/index.js
  src/pages/items/pistol-grips/index.js
  src/pages/items/provisions/index.js
  src/pages/items/rigs/index.js
  src/pages/items/suppressors/index.js
  src/pages/loot-tiers/index.js
  src/pages/maps/index.js
  src/pages/start/index.js
  src/pages/wipe-length/index.js
  src/translations/de/translation.json
  src/translations/en/translation.json
  src/translations/ru/translation.json
Labels: enhancement, UI, language

#116 Set the html lang attribute on language change
  src/App.js
Labels: language

#114 fix fee calculation
  src/modules/best-price.js
Labels: bug

#118 Use lang with api queries
  package.json
  public/images/барахольщик-icon.jpg
  public/images/егерь-icon.jpg
  public/images/лыжник-icon.jpg
  public/images/механик-icon.jpg
  public/images/миротворец-icon.jpg
  public/images/прапор-icon.jpg
  public/images/скупщик-icon.jpg
  public/images/терапевт-icon.jpg
  scripts/translate-trader-icons.js
  src/features/items/do-fetch-items.js
  src/modules/lang-helpers.js
Labels: enhancement, language

#96 Fully remove banner
  src/components/menu/index.js
Labels: hold

#122 fix langCode not formatting non US lang codes
  src/modules/lang-helpers.js
Labels: bug

#123 Add Fixed Supported Language File 🌐
  README.md
  src/data/supported-languages.json
  src/modules/lang-helpers.js
Labels: bug, language

#126 update fetchHideout to use hideoutStations
  src/components/items-for-hideout/index.js
  src/features/hideout/hideoutSlice.js
  src/pages/hideout/index.js
Labels: enhancement

#140 DropDown Menu Temp Fix
  src/components/menu/index.css
Labels: bug

#141 add lua (luvit) example to api-docs
  src/pages/api-docs/index.js
Labels: documentation, UI

#151 General Improvements
  src/components/barters-table/index.js
  src/components/contained-items-list/index.js
  src/components/loading/index.js
  src/components/small-item-table/index.js
  src/data/maps.json
  src/features/crafts/craftsSlice.js
  src/modules/format-cost-items.js
  src/pages/start/index.js
Labels: UI

#156 Map Updates 🗺️
  README.md
  docs/assets/homepage.png
  public/maps/shoreline-3d.jpg
  src/data/maps.json
Labels: enhancement

#157 Add Image Compression Action 🖼️ 🐘
  .github/workflows/images.yml
  docs/assets/homepage.png
  public/images/ammo-chart.jpg
  public/images/backpacks-table.jpg
  public/images/glasses-table.jpg
  public/images/jaeger-icon.jpg
  public/images/mechanic-icon.jpg
  public/images/peacekeeper-icon.jpg
  public/images/prapor-icon.jpg
  public/images/ragman-icon.jpg
  public/images/rigs-table-thumbnail.jpg
  public/images/skier-icon.jpg
  public/images/therapist-icon.jpg
  public/images/барахольщик-icon.jpg
  public/images/егерь-icon.jpg
  public/images/лыжник-icon.jpg
  public/images/механик-icon.jpg
  public/images/миротворец-icon.jpg
  public/images/прапор-icon.jpg
  public/images/терапевт-icon.jpg
  public/maps/customs-2d.jpg
  public/maps/factory.jpg
Labels: enhancement

#168 Added weight column to items/armor
  src/components/small-item-table/index.js
  src/pages/items/armor/index.js
Labels: enhancement

#172 Tooltip Improvements
  src/App.css
  src/components/barter-tooltip/index.css
  src/components/barter-tooltip/index.js
  src/components/small-item-table/index.js
  src/pages/items/glasses/index.js
  src/pages/items/helmets/index.js
Labels: UI

#176 Translation IT
  src/i18n.js
  src/pages/settings/index.js
  src/translations/it/translation.json
Labels: language

#177 add more translations info to readme
  README.md
Labels: documentation

#178 init all new langs we wish to support
  src/i18n.js
  src/pages/settings/index.js
  src/translations/es/translation.json
  src/translations/fr/translation.json
  src/translations/ja/translation.json
  src/translations/pl/translation.json
Labels: language
