Repository the-hideout/tarkov-dev, pull requests merged in 2023-03, with the labels that each got.

#409 Update Actions CI
  .github/CODEOWNERS
  .github/workflows/branch-deploy.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
  .github/workflows/new-pr.yml
  .node-version
Labels: dependencies

#404 Interface improvements
  src/components/barters-table/index.js
  src/components/cost-items-cell/index.js
  src/components/crafts-table/index.js
  src/components/item-image/index.js
  src/components/quest-items-cell/index.css
  src/components/quest-items-cell/index.js
  src/components/quest-table/index.js
  src/components/reward-cell/index.js
  src/components/small-item-table/index.js
  src/components/trader-image/index.css
  src/components/trader-image/index.js
  src/features/items/do-fetch-items.js
  src/features/quests/do-fetch-quests.js
  src/modules/format-cost-items.js
  src/pages/bitcoin-farm-calculator/index.js
  src/pages/items/guns/index.js
  src/pages/quest/index.js
  src/pages/start/index.js
  src/pages/trader/index.js
  src/translations/en/properties.json
Labels: enhancement, UI

#411 Trader spend table fix
  src/components/small-item-table/index.js
Labels: bug

#414 Calculate quest cash rewards using intel center level
  src/pages/quest/index.js
Labels: enhancement

#416 ja & it translations
  package-lock.json
  package.json
  src/App.js
  src/components/quest-items-cell/index.js
  src/components/small-item-table/index.js
  src/i18n.js
  src/pages/items/rigs/index.js
  src/pages/maps/index.js
  src/translations/de/translation.json
  src/translations/en/translation.json
  src/translations/es/translation.json
  src/translations/fr/translation.json
  src/translations/it/bosses.json
  src/translations/it/maps.json
  src/translations/it/properties.json
  src/translations/it/translation.json
  src/translations/ja/bosses.json
  src/translations/ja/maps.json
  src/translations/ja/properties.json
  src/translations/ja/translation.json
  src/translations/pl/translation.json
  src/translations/pt/translation.json
  src/translations/ru/translation.json
Labels: language

#422 Collapsible Alert 🔔
  package-lock.json
  package.json
  src/components/menu/alert-config.js
  src/components/menu/index.js
Labels: enhancement, UI
