Repository the-hideout/tarkov-dev, pull requests merged in 2023-01, with the labels that each got.

#336 bump branch deploy version
  .github/workflows/branch-deploy.yml
Labels: dependencies

#334 JSON Validation
  .github/workflows/ci.yml
  src/translations/remove_equal_key_value.py
Labels: enhancement

#339 Fix Discord widget animation.
  src/components/footer/index.css
Labels: enhancement

#335 Updated german translation
  src/translations/de/translation.json
Labels: language

#340 PL: fix typo
  src/translations/pl/translation.json
Labels: language

#350 Some more improvements to the german translation
  src/translations/de/translation.json
Labels: language
