Repository the-hideout/tarkov-dev, pull requests merged in 2023-02, with the labels that each got.

#354 add portuguese translation, fix 2 typos in en
  src/i18n.js
  src/translations/en/translation.json
  src/translations/pt/translation.json
  src/translations/remove_equal_key_value.py
Labels: language

#359 Offline Development
  scripts/build-sitemap.js
  scripts/cache-api-data.mjs
  scripts/get-contributors.js
Labels: enhancement

#361 PL: update translations
  src/translations/pl/translation.json
Labels: language

#365 More translations
  i18next-parser.config.mjs
  src/App.css
  src/components/Graph.jsx
  src/components/footer/index.js
  src/components/price-graph/index.js
  src/i18n.js
  src/modules/property-format.js
  src/pages/about/index.css
  src/pages/about/index.js
  src/pages/ammo/index.js
  src/pages/api-docs/index.js
  src/pages/api-users/index.js
  src/pages/barters/index.js
  src/pages/bosses/boss/index.js
  src/pages/bosses/index.js
  src/pages/control/index.js
  src/pages/crafts/index.js
  src/pages/item/index.js
  src/pages/loot-tiers/index.js
  src/pages/traders/index.js
  src/pages/traders/trader/index.js
  src/translations/de/translation.json
  src/translations/en/bosses.json
  src/translations/en/properties.json
  src/translations/en/translation.json
  src/translations/es/translation.json
  src/translations/fr/translation.json
  src/translations/it/translation.json
  src/translations/ja/translation.json
  src/translations/pl/translation.json
  src/translations/pt/translation.json
  src/translations/remove_equal_key_value.py
  src/translations/ru/bosses.json
  src/translations/ru/properties.json
  src/translations/ru/translation.json
Labels: language

#381 Merge Commit Strategy
  .github/workflows/branch-deploy.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
  .github/workflows/new-pr.yml
Labels: enhancement

#392 SEO, CSS and more
  package-lock.json
  package.json
  scripts/build-sitemap.js
  src/App.css
  src/App.js
  src/components/Map.jsx
  src/components/Time.jsx
  src/components/barter-tooltip/index.js
  src/components/barters-table/index.js
  src/components/crafts-table/index.js
  src/components/item-cost/index.js
  src/components/item-search/index.js
  src/components/items-summary-table/index.js
  src/components/menu/index.js
  src/components/quest-table/index.js
  src/components/reward-cell/index.js
  src/components/small-item-table/index.js
  src/components/trader-price-cell/index.js
  src/data/maps.json
  src/features/barters/do-fetch-barters.js
  src/features/crafts/do-fetch-crafts.js
  src/features/items/do-fetch-items.js
  src/features/maps/queries.js
  src/pages/boss/index.css
  src/pages/boss/index.js
  src/pages/item/index.js
  src/pages/items/index.css
  src/pages/items/index.js
  src/pages/items/pistol-grips/index.js
  src/pages/items/suppressors/index.js
  src/pages/maps/index.js
  src/pages/quest/index.js
  src/pages/start/index.js
  src/pages/trader/index.css
  src/pages/trader/index.js
  src/pages/traders/index.js
Labels: bug, enhancement, dependencies, UI, language
